import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {filterSpeechMetadata} from '../ocr-speech-boundary.js';
const line=(textRole,pageRegion,text='text')=>({textRole,pageRegion,text,speaker:'Narrator'});
const metadata=dialogues=>({title:'story',panels:[{panelNumber:4,dialogues}]});
test('page footer and margin production credits cannot reach speech',()=>{
 const input=metadata([line('page_credit','page_footer','Generated by an illustration tool'),line('page_credit','page_margin','Publisher website'),line('dialogue','panel','Hello')]);
 const result=filterSpeechMetadata(input);assert.equal(result.excluded,2);assert.deepEqual(result.metadata.panels[0].dialogues,[input.panels[0].dialogues[2]]);assert.equal(input.panels[0].dialogues.length,3);
});
test('genuine bottom narration, story URL, dialogue and SFX remain allowed',()=>{
 const input=metadata([line('narration','page_footer','That was the end of our journey.'),line('story_text','page_footer','https://example.org/map'),line('dialogue','panel','Generated by the robot?'),line('sfx','panel','BANG'),line('story_text','panel','Tool manual: https://example.org/manual'),line('page_credit','panel','The fictional artist signs a painting')]);
 const result=filterSpeechMetadata(input);assert.equal(result.excluded,0);assert.deepEqual(result.metadata,input);
});
test('missing role/position evidence fails closed without another model call',()=>{
 for(const invalid of [{text:'unknown'},line('narration','unknown'),line('unknown','panel')])assert.throws(()=>filterSpeechMetadata(metadata([invalid])),/role\/page region/);
});
test('existing real generation retains all 11 story lines and removes the 2 visually verified page credits',()=>{
 const data=JSON.parse(readFileSync(new URL('./fixtures/ocr-footer-regression.json',import.meta.url),'utf8'));
 const annotated=data.dialogues;
 const result=filterSpeechMetadata(metadata(annotated));assert.equal(result.excluded,2);assert.equal(result.metadata.panels[0].dialogues.length,11);
});
